export default [
    {
        name:"particlesTexture",
        type:"texture",
        path:"../../textures/5.webp",
        category:"particles"
    },
    {
        name:"gradientTexture",
        type:"texture",
        path:"../../textures/3.webp",
        category:"general"
    },
    {
        name:"astronautModel",
        type:"gltf",
        path:"../../models/Astronaut.glb",
        category:"model"
    },
    {
        name:"planetModel",
        type:"gltf",
        path:"../../models/Planet.glb",
        category:"model"
    }
]