export default [
    {
        name:"particlesTexture",
        type:"texture",
        path:"../../textures/starTexture.png",
        category:"particles"
    },
    {
        name:"environmentMapTexture",
        type:"hdr",
        path:"../../textures/EnvironmentMap.hdr",
        category:"general"
    },
    {
        name:"astronautModel",
        type:"gltf",
        path:"../../models/Astronaut.glb",
        category:"model"
    },
    {
        name:"planetModel",
        type:"gltf",
        path:"../../models/Planet.glb",
        category:"model"
    }
]