export default [
    {
        name:"particlesTexture",
        type:"texture",
        path:"static/textures/5.webp",
        category:"particles"
    },
    {
        name:"gradientTexture",
        type:"texture",
        path:"static/textures/3.webp",
        category:"general"
    },
    {
        name:"astronautModel",
        type:"gltf",
        path:"static/models/Astronaut.glb",
        category:"model",
    }
]